import Head from "next/head";
import { useRef, useState } from "react";
import InitForm from "../Components/InitForm";
import { useRouter } from "next/router";

export default function Home(): JSX.Element {
  return (
    <>
      <Head>
        <title>Sugges</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <InitForm />
    </>
  );
}
