import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { BsFillMoonStarsFill, BsQuestionCircleFill } from "react-icons/bs";
import { MutableRefObject, useRef, useState } from "react";
import Link from "next/link";
import DisplayShows from "../Components/DisplayShows";
import InitForm from "../Components/InitForm";

const inter = Inter({ subsets: ["latin"] });

export default function Home(): JSX.Element {
  const [darkMode, setDarkMode] = useState(false);
  const [sugges, setSugges] = useState(false);

  const c1 = useRef<HTMLInputElement>(null!);
  const c2 = useRef<HTMLInputElement>(null!);
  const c3 = useRef<HTMLInputElement>(null!);

  const onSuggesClick = () => {
    if (
      c1.current.value == "" ||
      c2.current.value == "" ||
      c3.current.value == ""
    ) {
      setSugges(false);
      alert("Please fill all the fields");
    } else {
      setSugges(true);
    }
  };

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Sugges</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white flex flex-col dark:bg-gray-900">
        <section>
          <nav className="py-10 px-10 flex justify-between bg-teal-900">
            <h1 className="text-xl font-bold font-sans text-white">Sugges</h1>
            <ul className="flex items-center">
              <li className="cursor-pointer text-2xl">
                <BsFillMoonStarsFill
                  color="white"
                  onClick={() => setDarkMode(!darkMode)}
                />
              </li>
              <li className="cursor-pointer text-2xl ml-9">
                <BsQuestionCircleFill color="white" />
              </li>
            </ul>
          </nav>
        </section>
        {!sugges && (
          <InitForm
            c1={c1}
            c2={c2}
            c3={c3}
            setSuggess={setSugges}
            onSuggessClick={onSuggesClick}
          />
        )}
        {sugges && (
          <DisplayShows setSuggess={setSugges} c1={c1} c2={c2} c3={c3} />
        )}
      </main>
    </div>
  );
}
